# Generated by Django 5.2 on 2025-11-11 18:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название издательства')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('founded', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год основания')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальная длина 100 символов', max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, help_text='Необязательное поле', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Пользовательская запись')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Knife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название Ножи')),
                ('description', models.TextField(verbose_name='Описание Ножи')),
                ('min_players', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Минимальная партия')),
                ('max_players', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальная партия')),
                ('play_time', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Среднее время Ножи (минуты)')),
                ('age_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(18)], verbose_name='Рекомендуемый возраст')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (руб)')),
                ('steel', models.CharField(help_text='Например, VG-10, AUS-8, X50CrMoV15', max_length=100, verbose_name='Сталь')),
                ('blade_length_mm', models.PositiveIntegerField(help_text='Например, 180', verbose_name='Длина лезвия (мм)')),
                ('purpose', models.CharField(choices=[('CHEF', 'Шефский'), ('SANTOKU', 'Сантоку'), ('UTILITY', 'Универсальный'), ('PARING', 'Овощной/Нож для чистки'), ('BREAD', 'Хлебный'), ('BONING', 'Филе/Разделочный'), ('CLEAVER', 'Тяпка')], max_length=16, verbose_name='Назначение')),
                ('edge_angle_deg', models.PositiveSmallIntegerField(help_text='Обычно 12–20° на сторону', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(40)], verbose_name='Угол заточки (°)')),
                ('handle_material', models.CharField(help_text='Например, микарта, дерево, пластик', max_length=100, verbose_name='Материал рукояти')),
                ('manufacturer_country', models.CharField(blank=True, max_length=100, verbose_name='Страна-производитель')),
                ('image', models.ImageField(blank=True, null=True, upload_to='knives/covers/', verbose_name='Фото ножа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knifes', to='knifestore.category', verbose_name='Категория')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knifes', to='knifestore.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Нож',
                'verbose_name_plural': 'Ножи',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='new', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_address', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knifestore.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('knife', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knifestore.knife')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='knifestore.order')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('country', models.CharField(default='Россия', max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
                'ordering': ['last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(fields=('first_name', 'last_name', 'birth_date'), name='unique_designer')],
            },
        ),
        migrations.AddField(
            model_name='knife',
            name='designers',
            field=models.ManyToManyField(related_name='knifes', to='knifestore.series', verbose_name='Серия'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('last_restocked', models.DateTimeField(auto_now=True, verbose_name='Последнее пополнение')),
                ('knife', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='knifestore.knife', verbose_name='Ножи')),
            ],
            options={
                'verbose_name': 'Складской остаток',
                'verbose_name_plural': 'Складские остатки',
                'ordering': ['-last_restocked'],
            },
        ),
        migrations.AddIndex(
            model_name='knife',
            index=models.Index(fields=['title'], name='knife_title_idx'),
        ),
        migrations.AddIndex(
            model_name='knife',
            index=models.Index(fields=['price'], name='knife_price_idx'),
        ),
        migrations.AddIndex(
            model_name='knife',
            index=models.Index(fields=['release_date'], name='knife_release_date_idx'),
        ),
    ]
