# Generated by Django 5.2 on 2025-04-30 08:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальная длина 100 символов', max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, help_text='Необязательное поле', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название издательства')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('founded', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год основания')),
            ],
            options={
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Пользовательская запись')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('country', models.CharField(default='Россия', max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Дизайнер',
                'verbose_name_plural': 'Дизайнеры',
                'ordering': ['last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(fields=('first_name', 'last_name', 'birth_date'), name='unique_designer')],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название игры')),
                ('description', models.TextField(verbose_name='Описание игры')),
                ('min_players', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Минимальное количество игроков')),
                ('max_players', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальное количество игроков')),
                ('play_time', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Среднее время игры (минуты)')),
                ('age_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(18)], verbose_name='Рекомендуемый возраст')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (руб)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/covers/', verbose_name='Обложка игры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='firstproject.category', verbose_name='Категория')),
                ('designers', models.ManyToManyField(related_name='games', to='firstproject.designer', verbose_name='Дизайнеры')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='firstproject.publisher', verbose_name='Издатель')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма заказа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='firstproject.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за единицу')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='firstproject.game', verbose_name='Игра')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='firstproject.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('last_restocked', models.DateTimeField(auto_now=True, verbose_name='Последнее пополнение')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='firstproject.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Складской остаток',
                'verbose_name_plural': 'Складские остатки',
                'ordering': ['-last_restocked'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_created_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'game'), name='unique_order_item'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title'], name='game_title_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['price'], name='game_price_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['release_date'], name='game_release_date_idx'),
        ),
    ]
